//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stratagepagecondition
    {
        public int stpid { get; set; }
        public string StpName { get; set; }
        public string StpSelector { get; set; }
        public string StpAttribute { get; set; }
        public Nullable<bool> StpText { get; set; }
        public int StpStratage { get; set; }
    
        public virtual stratege stratege { get; set; }
    }
}
